# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Yash Mittal
email: yashmittal2009@gmail.com
description: >-
  Yash Mittal's personal website. He's a senior studying Computer Science at Bucknell University.
baseurl: "" # Set this to "/" if the site is hosted in a subdirectory
url: "https://yashmittal.me"
github_username: ymittal
facebook_username: imyashmittal
linkedin_username: ymittal

include:
  - pages

permalink: pretty
future: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  # Uncomment the line below to enable jekyll-sitemap if it works for your setup
  # - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
# Optional configurations for jekyll-sitemap and other plugins can go here.
